/**
 * AllFreeAlerts — Voice Reel Generator
 * Generates a reel video WITH voiceover narration using Edge TTS
 * This is the "second daily video" — music-only reel is generated by generate_reel.js
 *
 * Usage: node generate_voice_reel.js [--dry-run]
 * Requires: ffmpeg, python (for beat generation), edge-tts (pip install edge-tts), puppeteer
 */

const { execSync, spawnSync } = require('child_process');
const fs = require('fs');
const path = require('path');

// ── Config ──
const DRY_RUN = process.argv.includes('--dry-run') || process.argv.includes('--preview');
const OUT_DIR = path.join(__dirname, 'tmp_videos');
const BEAT_FILE = path.join(OUT_DIR, 'beat.wav');
const VOICE_REEL_FILE = path.join(OUT_DIR, 'voice_reel.mp4');

// ── Brand ──
const COLORS = { teal: '#0ABAB5', orange: '#FF6F3C', gold: '#F5A623' };
const CAT_COLORS = { Sweepstakes: COLORS.teal, Freebies: COLORS.orange, Settlements: COLORS.gold };
const CAT_EMOJI = { Sweepstakes: '🎉', Freebies: '🎁', Settlements: '💰' };
const CAT_LABELS = { Sweepstakes: 'Sweepstakes', Freebies: 'Free Stuff', Settlements: 'Settlement' };

const THEMES = [
  { name: 'midnight', bg: 'linear-gradient(160deg, #0e1628 0%, #1a1a2e 50%, #0e1628 100%)' },
  { name: 'sunset', bg: 'linear-gradient(160deg, #1a0a2e 0%, #2d1b4e 40%, #1a0a2e 100%)' },
  { name: 'ocean', bg: 'linear-gradient(160deg, #0a1628 0%, #0d2137 50%, #0a1628 100%)' },
  { name: 'forest', bg: 'linear-gradient(160deg, #0a1a14 0%, #0d2e1f 50%, #0a1a14 100%)' },
  { name: 'ember', bg: 'linear-gradient(160deg, #1a0f0a 0%, #2e1810 50%, #1a0f0a 100%)' },
  { name: 'slate', bg: 'linear-gradient(160deg, #1a1a1a 0%, #2a2a2a 50%, #1a1a1a 100%)' },
  { name: 'arctic', bg: 'linear-gradient(160deg, #0a1520 0%, #102838 50%, #0a1520 100%)' },
];

// Use different theme than music-only reel (offset by 3)
function getTodayTheme() {
  const day = Math.floor(Date.now() / 86400000);
  return THEMES[(day + 3) % THEMES.length];
}

function log(msg) { console.log(`[VoiceReel] ${msg}`); }

// ── Load data ──
function loadData() {
  try {
    return JSON.parse(fs.readFileSync(path.join(__dirname, 'data', 'results.json'), 'utf8'));
  } catch {
    try {
      const raw = fs.readFileSync(path.join(__dirname, 'site', 'data.json'), 'utf8');
      const key = 'aFa2026xK';
      const b = Buffer.from(raw, 'base64');
      const decoded = Buffer.from(b.map((v, i) => v ^ key.charCodeAt(i % key.length)));
      return JSON.parse(decoded.toString('utf8'));
    } catch { return []; }
  }
}

function loadHistory() {
  try { return JSON.parse(fs.readFileSync(path.join(__dirname, 'ig_fb_post_history.json'), 'utf8')); }
  catch { return { posted: [] }; }
}

// Pick DIFFERENT deals than the music-only reel (offset selection)
function pickItems() {
  const data = loadData();
  const history = loadHistory();
  const postedLinks = new Set(history.posted || []);
  const picks = [];

  for (const cat of ['Sweepstakes', 'Freebies', 'Settlements']) {
    let catItems = data.filter(i => i.category === cat && !postedLinks.has(i.link));
    if (cat === 'Settlements') {
      catItems = catItems.filter(i => !i.scope || i.scope === 'nationwide');
    }
    if (catItems.length > 1) {
      // Use different offset than music reel to pick different deals
      const day = Math.floor(Date.now() / 86400000);
      const idx = (day * 11 + picks.length * 17 + 5) % catItems.length;
      picks.push({ category: cat, item: catItems[idx] });
    } else if (catItems.length === 1) {
      picks.push({ category: cat, item: catItems[0] });
    }
  }
  return picks;
}

// ── Generate voiceover scripts ──
function buildVoiceScripts(picks) {
  const totalData = loadData();
  const scripts = [];

  // Intro narration
  scripts.push({
    type: 'intro',
    text: `Here are today's top free stuff picks from All Free Alerts. ${totalData.length} plus active deals, found for you.`
  });

  // Deal narrations
  for (const { category, item } of picks) {
    const label = CAT_LABELS[category];
    const title = (item.title || '').replace(/[|—–]/g, ',').slice(0, 120);
    const summary = (item.prize_summary || item.description || '').slice(0, 100);

    let text = `${label}: ${title}.`;
    if (summary) text += ` ${summary}.`;

    // Add deadline urgency
    const deadline = item.end_date || item.deadline || '';
    if (deadline) {
      const d = new Date(deadline);
      if (!isNaN(d)) {
        const days = Math.max(0, Math.ceil((d - new Date()) / 86400000));
        if (days <= 14) text += ` Hurry, only ${days} days left!`;
      }
    }

    scripts.push({ type: 'deal', category, text });
  }

  // Outro narration
  scripts.push({
    type: 'outro',
    text: 'Follow All Free Alerts for daily deals. Link in bio for the full list.'
  });

  return scripts;
}

// ── Generate TTS audio files using Edge TTS ──
async function generateVoiceover(scripts) {
  log('Generating voiceover audio...');
  const voiceFiles = [];
  const voice = 'en-US-GuyNeural'; // Clear male voice

  for (let i = 0; i < scripts.length; i++) {
    const outFile = path.join(OUT_DIR, `voice_${i}.mp3`);
    const text = scripts[i].text.replace(/'/g, "'").replace(/"/g, '\\"');

    try {
      const cmd = `edge-tts --text "${text}" --voice ${voice} --rate=+5% --write-media "${outFile}"`;
      execSync(cmd, { stdio: 'pipe', timeout: 15000 });
      voiceFiles.push(outFile);
      log(`  Voice ${i}: ${scripts[i].type} (${scripts[i].text.substring(0, 50)}...)`);
    } catch (e) {
      log(`  Voice ${i} failed: ${e.message}`);
      // Create 3s silence as fallback
      execSync(`ffmpeg -y -f lavfi -i anullsrc=r=44100:cl=mono -t 3 "${outFile}"`, { stdio: 'pipe' });
      voiceFiles.push(outFile);
    }
  }

  // Get duration of each voice clip
  const durations = [];
  for (const file of voiceFiles) {
    try {
      const probe = execSync(`ffprobe -v error -show_entries format=duration -of csv=p=0 "${file}"`, { encoding: 'utf8' }).trim();
      durations.push(Math.max(parseFloat(probe) || 3, 2.5)); // minimum 2.5s per slide
    } catch {
      durations.push(3);
    }
  }

  return { voiceFiles, durations };
}

// ── Slide HTML generators ──
function generateIntroSlideHTML(count) {
  const theme = getTodayTheme();
  const today = new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' });

  return `<!DOCTYPE html><html><head><style>
    *{margin:0;padding:0;box-sizing:border-box}
    body{width:1080px;height:1920px;display:flex;justify-content:center;align-items:center;
      background:${theme.bg};font-family:'Segoe UI',Arial,sans-serif;overflow:hidden}
    .slide{width:1080px;height:1920px;display:flex;flex-direction:column;justify-content:center;
      align-items:center;padding:80px 60px;position:relative}
    .bg-circle{position:absolute;border-radius:50%;opacity:0.1}
    .bg-circle.c1{width:800px;height:800px;background:${COLORS.teal};top:-200px;right:-200px}
    .bg-circle.c2{width:500px;height:500px;background:${COLORS.orange};bottom:-100px;left:-150px}
    .logo{font-size:56px;font-weight:900;color:white;letter-spacing:-1px;margin-bottom:20px;z-index:1}
    .logo span{color:${COLORS.teal}}
    .tagline{font-size:34px;color:rgba(255,255,255,0.6);margin-bottom:60px;z-index:1}
    .big{font-size:110px;font-weight:900;color:white;z-index:1;margin-bottom:10px;
      text-shadow:0 4px 30px rgba(10,186,181,0.4)}
    .big-sub{font-size:36px;color:${COLORS.teal};font-weight:700;z-index:1;margin-bottom:60px}
    .today{font-size:28px;color:rgba(255,255,255,0.4);z-index:1}
    .wave{position:absolute;bottom:150px;font-size:60px;z-index:1}
  </style></head><body>
  <div class="slide">
    <div class="bg-circle c1"></div><div class="bg-circle c2"></div>
    <div class="logo">AllFree<span>Alerts</span></div>
    <div class="tagline">${today}</div>
    <div class="big">${count}+</div>
    <div class="big-sub">Active Deals Today</div>
    <div class="today">Free Stuff, Found For You</div>
    <div class="wave">🔊</div>
  </div>
  </body></html>`;
}

function generateDealSlideHTML(item, category, slideNum, totalSlides) {
  const title = (item.title || '').slice(0, 100);
  const summary = (item.prize_summary || item.description || '').slice(0, 100);
  const color = CAT_COLORS[category] || COLORS.teal;
  const emoji = CAT_EMOJI[category] || '🔔';
  const catLabel = category === 'Freebies' ? 'FREE STUFF' : category.toUpperCase();
  const theme = getTodayTheme();

  const deadline = item.end_date || item.deadline || '';
  let deadlineHTML = '';
  if (deadline) {
    const d = new Date(deadline);
    if (!isNaN(d)) {
      const days = Math.max(0, Math.ceil((d - new Date()) / 86400000));
      if (days <= 14) {
        deadlineHTML = `<div class="deadline">⏰ ${days} days left</div>`;
      }
    }
  }

  return `<!DOCTYPE html><html><head><style>
    *{margin:0;padding:0;box-sizing:border-box}
    body{width:1080px;height:1920px;display:flex;justify-content:center;align-items:center;
      background:${theme.bg};font-family:'Segoe UI',Arial,sans-serif;overflow:hidden}
    .slide{width:1080px;height:1920px;display:flex;flex-direction:column;justify-content:center;
      align-items:center;padding:80px 60px;position:relative}
    .bg-circle{position:absolute;border-radius:50%;opacity:0.08}
    .bg-circle.c1{width:600px;height:600px;background:${color};top:-100px;right:-150px}
    .bg-circle.c2{width:400px;height:400px;background:${color};bottom:-50px;left:-100px}
    .top-bar{position:absolute;top:80px;display:flex;align-items:center;gap:15px;z-index:2}
    .logo{font-size:28px;font-weight:900;color:white;letter-spacing:-0.5px}
    .logo span{color:${color}}
    .slide-num{background:rgba(255,255,255,0.1);color:rgba(255,255,255,0.6);padding:6px 16px;
      border-radius:20px;font-size:18px;font-weight:600}
    .emoji{font-size:100px;margin-bottom:30px;z-index:1}
    .badge{background:${color};color:white;padding:14px 40px;border-radius:60px;font-size:26px;
      font-weight:800;letter-spacing:3px;margin-bottom:40px;z-index:1;box-shadow:0 8px 30px ${color}66}
    .title{font-size:52px;font-weight:800;color:white;text-align:center;line-height:1.25;z-index:1;
      margin-bottom:25px;text-shadow:0 4px 20px rgba(0,0,0,0.3);max-width:900px}
    .sub{font-size:30px;color:rgba(255,255,255,0.75);text-align:center;z-index:1;line-height:1.5;max-width:850px}
    .deadline{margin-top:30px;background:rgba(255,59,48,0.2);border:2px solid rgba(255,59,48,0.4);
      color:#ff6b6b;padding:12px 30px;border-radius:40px;font-size:24px;font-weight:700;z-index:1}
    .cta{position:absolute;bottom:120px;z-index:2;display:flex;flex-direction:column;align-items:center;gap:15px}
    .cta-btn{background:${color};color:white;padding:18px 50px;border-radius:50px;font-size:28px;
      font-weight:800;box-shadow:0 8px 30px ${color}66}
    .cta-sub{color:rgba(255,255,255,0.5);font-size:20px;font-weight:500}
    .brand{position:absolute;bottom:50px;font-size:22px;color:rgba(255,255,255,0.3);font-weight:600;z-index:2}
    .speaker{position:absolute;top:85px;right:80px;font-size:30px;opacity:0.5}
  </style></head><body>
  <div class="slide">
    <div class="bg-circle c1"></div><div class="bg-circle c2"></div>
    <div class="top-bar">
      <div class="logo">AllFree<span>Alerts</span></div>
      <div class="slide-num">${slideNum}/${totalSlides}</div>
    </div>
    <div class="speaker">🔊</div>
    <div class="emoji">${emoji}</div>
    <div class="badge">${catLabel} ALERT</div>
    <div class="title">${title}</div>
    ${summary ? `<div class="sub">${summary}</div>` : ''}
    ${deadlineHTML}
    <div class="cta">
      <div class="cta-btn">See Details →</div>
      <div class="cta-sub">Link in bio</div>
    </div>
    <div class="brand">allfreealerts.com</div>
  </div>
  </body></html>`;
}

function generateOutroSlideHTML() {
  const theme = getTodayTheme();
  return `<!DOCTYPE html><html><head><style>
    *{margin:0;padding:0;box-sizing:border-box}
    body{width:1080px;height:1920px;display:flex;justify-content:center;align-items:center;
      background:${theme.bg};font-family:'Segoe UI',Arial,sans-serif;overflow:hidden}
    .slide{width:1080px;height:1920px;display:flex;flex-direction:column;justify-content:center;
      align-items:center;padding:80px 60px;position:relative}
    .bg-circle{position:absolute;border-radius:50%;opacity:0.1}
    .bg-circle.c1{width:700px;height:700px;background:${COLORS.teal};top:-100px;left:-200px}
    .bg-circle.c2{width:400px;height:400px;background:${COLORS.gold};bottom:-50px;right:-100px}
    .emoji{font-size:80px;margin-bottom:30px;z-index:1}
    .headline{font-size:48px;font-weight:800;color:white;text-align:center;line-height:1.3;z-index:1;margin-bottom:20px}
    .sub{font-size:28px;color:rgba(255,255,255,0.6);text-align:center;z-index:1;margin-bottom:50px;line-height:1.5}
    .cta-btn{background:${COLORS.teal};color:white;padding:22px 60px;border-radius:60px;font-size:32px;
      font-weight:800;z-index:1;box-shadow:0 8px 30px rgba(10,186,181,0.4);margin-bottom:15px}
    .cta-small{font-size:22px;color:rgba(255,255,255,0.4);z-index:1}
    .handles{position:absolute;bottom:100px;z-index:1;display:flex;flex-direction:column;align-items:center;gap:8px}
    .handle{font-size:22px;color:rgba(255,255,255,0.4);font-weight:600}
  </style></head><body>
  <div class="slide">
    <div class="bg-circle c1"></div><div class="bg-circle c2"></div>
    <div class="emoji">🔔</div>
    <div class="headline">Follow For<br>Daily Deals</div>
    <div class="sub">New free stuff every single day<br>Never miss a deal again</div>
    <div class="cta-btn">Follow @allfreealerts</div>
    <div class="cta-small">Link in bio for all deals</div>
    <div class="handles">
      <div class="handle">📸 @allfreealerts</div>
      <div class="handle">🌐 allfreealerts.com</div>
    </div>
  </div>
  </body></html>`;
}

// ── Render slides with Puppeteer ──
async function renderSlides(picks) {
  const puppeteer = require('puppeteer');
  const browser = await puppeteer.launch({ headless: 'new', args: ['--no-sandbox'] });
  const page = await browser.newPage();
  await page.setViewport({ width: 1080, height: 1920 });

  if (!fs.existsSync(OUT_DIR)) fs.mkdirSync(OUT_DIR, { recursive: true });

  const slides = [];
  const totalSlides = picks.length;
  const totalData = loadData();

  // Intro
  const introHTML = generateIntroSlideHTML(totalData.length);
  const introFile = path.join(OUT_DIR, 'vslide_intro.html');
  const introPNG = path.join(OUT_DIR, 'vslide_intro.png');
  fs.writeFileSync(introFile, introHTML);
  await page.goto('file:///' + introFile.replace(/\\/g, '/'));
  await page.screenshot({ path: introPNG });
  fs.unlinkSync(introFile);
  slides.push(introPNG);
  log('  Rendered intro slide');

  // Deal slides
  for (let i = 0; i < picks.length; i++) {
    const { category, item } = picks[i];
    const html = generateDealSlideHTML(item, category, i + 1, totalSlides);
    const htmlFile = path.join(OUT_DIR, `vslide_${i}.html`);
    const pngFile = path.join(OUT_DIR, `vslide_${i}.png`);
    fs.writeFileSync(htmlFile, html);
    await page.goto('file:///' + htmlFile.replace(/\\/g, '/'));
    await page.screenshot({ path: pngFile });
    fs.unlinkSync(htmlFile);
    slides.push(pngFile);
    log(`  Rendered deal slide ${i + 1}: ${item.title.substring(0, 40)}...`);
  }

  // Outro
  const outroHTML = generateOutroSlideHTML();
  const outroFile = path.join(OUT_DIR, 'vslide_outro.html');
  const outroPNG = path.join(OUT_DIR, 'vslide_outro.png');
  fs.writeFileSync(outroFile, outroHTML);
  await page.goto('file:///' + outroFile.replace(/\\/g, '/'));
  await page.screenshot({ path: outroPNG });
  fs.unlinkSync(outroFile);
  slides.push(outroPNG);
  log('  Rendered outro slide');

  await browser.close();
  return slides;
}

// ── Generate beat (reuse from generate_beat.py) ──
function generateBeat() {
  if (!fs.existsSync(OUT_DIR)) fs.mkdirSync(OUT_DIR, { recursive: true });
  if (fs.existsSync(BEAT_FILE)) {
    const stat = fs.statSync(BEAT_FILE);
    if (Date.now() - stat.mtimeMs < 86400000) {
      log('Reusing existing beat');
      return;
    }
  }
  log('Generating beat...');
  const pyCmd = process.platform === 'win32' ? 'python' : 'python3';
  const result = spawnSync(pyCmd, [path.join(__dirname, 'generate_beat.py'), BEAT_FILE], {
    stdio: 'pipe', timeout: 30000
  });
  if (result.status !== 0) {
    log('Beat generation failed, creating silent audio');
    execSync(`ffmpeg -y -f lavfi -i anullsrc=r=44100:cl=stereo -t 30 "${BEAT_FILE}"`, { stdio: 'pipe' });
  }
  log('Beat ready');
}

// ── Stitch video with voice + beat ──
function stitchVideo(slides, voiceFiles, durations) {
  log('Stitching video with voiceover...');

  // Add 1.5s padding to each voice duration for breathing room
  const slideDurations = durations.map(d => d + 1.5);
  const totalDur = slideDurations.reduce((a, b) => a + b, 0);
  log(`Total video duration: ${totalDur.toFixed(1)}s`);

  // Step 1: Create individual slide video clips (NO audio)
  const slideVideos = [];
  for (let i = 0; i < slides.length; i++) {
    const slideVid = path.join(OUT_DIR, `vclip_${i}.mp4`);
    const dur = slideDurations[i].toFixed(2);
    const zoomDir = i % 2 === 0 ? '1+0.0006*on' : '1.10-0.0006*on';
    const frames = Math.ceil(slideDurations[i] * 30);

    const cmd = `ffmpeg -y -loop 1 -t ${dur} -i "${slides[i]}" -filter_complex "[0:v]scale=1080:1920,zoompan=z='${zoomDir}':x='iw/2-(iw/zoom/2)':y='ih/2-(ih/zoom/2)':d=${frames}:s=1080x1920:fps=30[v]" -map "[v]" -t ${dur} -c:v libx264 -preset ultrafast -crf 26 -pix_fmt yuv420p -r 30 -an "${slideVid}"`;

    try {
      execSync(cmd, { stdio: 'pipe', timeout: 120000 });
      slideVideos.push(slideVid);
      log(`  Clip ${i} done (${dur}s)`);
    } catch (e) {
      log(`  Clip ${i} failed: ${e.stderr?.toString().split('\n').slice(-3).join('\n') || e.message}`);
      return false;
    }
  }

  // Step 2: Concatenate video clips (no audio)
  const listFile = path.join(OUT_DIR, 'voice_clips.txt');
  fs.writeFileSync(listFile, slideVideos.map(f => `file '${f.replace(/\\/g, '/')}'`).join('\n'));
  const silentVideo = path.join(OUT_DIR, 'voice_reel_silent.mp4');
  execSync(`ffmpeg -y -f concat -safe 0 -i "${listFile}" -c copy "${silentVideo}"`, { stdio: 'pipe', timeout: 30000 });
  log('Video concatenated');

  // Step 3: Create continuous voice track (pad each voice to slide duration, then concat)
  const voiceTrack = path.join(OUT_DIR, 'voice_track.wav');
  let voiceFilter = '';
  let voiceConcat = '';
  let voiceInputs = '';
  for (let i = 0; i < voiceFiles.length; i++) {
    voiceInputs += ` -i "${voiceFiles[i]}"`;
    voiceFilter += `[${i}:a]aformat=sample_fmts=fltp:sample_rates=44100:channel_layouts=mono,apad=whole_dur=${slideDurations[i].toFixed(2)},atrim=0:${slideDurations[i].toFixed(2)}[vp${i}];`;
    voiceConcat += `[vp${i}]`;
  }
  voiceFilter += `${voiceConcat}concat=n=${voiceFiles.length}:v=0:a=1[out]`;
  execSync(`ffmpeg -y${voiceInputs} -filter_complex "${voiceFilter}" -map "[out]" "${voiceTrack}"`, { stdio: 'pipe', timeout: 30000 });
  log('Voice track created');

  // Step 4: Mix continuous beat + continuous voice, merge with video
  const finalCmd = `ffmpeg -y -i "${silentVideo}" -i "${voiceTrack}" -i "${BEAT_FILE}" -filter_complex "[1:a]volume=1.0[voice];[2:a]volume=0.35,aloop=loop=-1:size=44100*25[beatloop];[voice][beatloop]amix=inputs=2:duration=first:dropout_transition=0[outa]" -map 0:v -map "[outa]" -c:v copy -c:a aac -b:a 128k -shortest "${VOICE_REEL_FILE}"`;

  try {
    execSync(finalCmd, { stdio: 'pipe', timeout: 60000 });
    const size = (fs.statSync(VOICE_REEL_FILE).size / 1024 / 1024).toFixed(1);
    log(`Voice reel generated: ${VOICE_REEL_FILE} (${size} MB)`);
    return true;
  } catch (e) {
    log('FFmpeg error: ' + (e.stderr?.toString().split('\n').slice(-10).join('\n') || e.message));
    return false;
  }
}

// ── Main ──
async function main() {
  log('=== Voice Reel Generator ===');
  log(`Mode: ${DRY_RUN ? 'DRY RUN' : 'LIVE'}`);

  if (!fs.existsSync(OUT_DIR)) fs.mkdirSync(OUT_DIR, { recursive: true });

  // Pick deals
  const picks = pickItems();
  if (picks.length === 0) {
    log('No deals to feature!');
    return;
  }
  log(`Picked ${picks.length} deals:`);
  picks.forEach(p => log(`  ${p.category}: ${p.item.title.substring(0, 50)}`));

  // Build voice scripts
  const scripts = buildVoiceScripts(picks);
  log('\nVoice scripts:');
  scripts.forEach((s, i) => log(`  ${i}: [${s.type}] ${s.text.substring(0, 60)}...`));

  // Generate voiceover audio
  const { voiceFiles, durations } = await generateVoiceover(scripts);
  log(`\nSlide durations: ${durations.map(d => d.toFixed(1) + 's').join(', ')}`);
  const totalDuration = durations.reduce((a, b) => a + b + 1.5, 0);
  log(`Total estimated duration: ${totalDuration.toFixed(1)}s`);

  if (DRY_RUN) {
    log('\nDRY RUN — skipping slide rendering and video stitching');
    log('Voice files generated in: ' + OUT_DIR);
    return;
  }

  // Generate beat
  generateBeat();

  // Render slides
  log('\nRendering slides...');
  const slides = await renderSlides(picks);

  // Stitch video
  const success = stitchVideo(slides, voiceFiles, durations);
  if (!success) {
    log('Video generation failed!');
    process.exit(1);
  }

  log('\nDone! Voice reel saved to: ' + VOICE_REEL_FILE);
}

main().catch(e => {
  console.error('Fatal error:', e);
  process.exit(1);
});
